<h1>Docker Container Error</h1>
<p>The following type of error can occur when adding a secondary service container for your job:</p>
<pre style="background-color: #f3f3f3; padding: 5px;">Unexpected environment preparation error: Error response from daemon: <br>OCI runtime create failed: container_linux.go:345: <br>starting container process caused "process_linux.go:303: <br>getting the final child's pid from pipe caused \"EOF\"": unknown</pre>
<p>This usually occurs due to a bad <a href="https://circleci.com/docs/2.0/configuration-reference/#docker" target="_blank" rel="noopener">command</a> being passed to one of the secondary service containers in your job. </p>
<p>The error message occurs due to the secondary service container crashing or exiting prematurely. This means CircleCI cannot get the PID from the Docker daemon and exits with a failure.</p>
<p>Ensure that the command and/or entrypoint are correct so that the container can spin up successfully. This can be be tested locally by using the <a href="https://circleci.com/docs/2.0/local-cli/#run-a-job-in-a-container-on-your-machine" target="_blank" rel="noopener">CircleCI CLI</a> to run the job locally and ensure Docker spins up all containers successfully. To resolve the error, check out the documentation for the docker image defined in your config to see which commands can be used at spin up.</p>
<p> </p>
<h2>Additional Resources</h2>
<ul>
    <li><a href="https://forums.docker.com/t/error-response-from-daemon-oci-runtime-create-failed-container-linux-go-starting-container-process-caused-exec-python/115382/3" target="_blank" rel="noopener">Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: “python”:</a></li>
</ul>